aws_region                  = "us-east-1"
environment                 = "prod"
project_name                = "infra-core"
owner                       = "devops-team"
cost_center                 = "CC-1042"
secret_name                 = "database/credentials"
secret_description          = "Database credentials managed by Terraform"
recovery_window_in_days     = 30
kms_key_id                  = null
create_secret_version       = true
secret_username             = "dbadmin"
secret_host                 = "database.example.com"
secret_port                 = "5432"
secret_dbname               = "myappdb"
create_policy               = false
allowed_read_principals     = ["arn:aws:iam::123456789012:role/app-role"]
enable_replication          = false
replica_regions             = ["us-west-2"]